# Generated by Django 3.2.9 on 2021-11-28 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique Primary Key of the object.', primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation time of the object. Automatically set at the time of creation.', verbose_name='Creation Time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated everytime any model field is updated.', verbose_name='Last Update Time')),
                ('is_active', models.BooleanField(default=True, help_text='Used to implement soft delete. If false, then object is considered deleted.', verbose_name='Is Active')),
                ('title', models.CharField(help_text='Title of the post.', max_length=255, verbose_name='Title')),
                ('body', models.TextField(help_text='Content of the post.', verbose_name='body')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_posts', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
