# Generated by Django 4.0 on 2022-01-08 13:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(help_text='Content of the post.', verbose_name='body'),
        ),
    ]
