# Generated by Django 3.2.9 on 2021-11-28 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_postcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcomments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation time of the object. Automatically set at the time of creation.', verbose_name='Creation Time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated everytime any model field is updated.', verbose_name='Last Update Time')),
                ('is_active', models.BooleanField(default=True, help_text='Used to implement soft delete. If false, then object is considered deleted.', verbose_name='Is Active')),
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='post.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postlikes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post_like',
            },
        ),
        migrations.CreateModel(
            name='PostCommentLike',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation time of the object. Automatically set at the time of creation.', verbose_name='Creation Time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated everytime any model field is updated.', verbose_name='Last Update Time')),
                ('is_active', models.BooleanField(default=True, help_text='Used to implement soft delete. If false, then object is considered deleted.', verbose_name='Is Active')),
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='post.postcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcommentlikes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'postcomment_like',
            },
        ),
    ]
